language: objective-c
osx_image: xcode8
sudo: false
rvm:
  - 2.3

cache:
  - bundler
  - cocoapods

env:
  global:
    - WORKSPACE="MoyaSugar.xcworkspace"
    - IOS_SDK="iphonesimulator10.0"
    - MACOS_SDK="macosx10.12"
    - TVOS_SDK="appletvsimulator10.0"
    - WATCHOS_SDK="watchsimulator3.0"
  matrix:
    - SCHEME="MoyaSugar-iOS"        SDK="$IOS_SDK"      ACTION="test"
    - SCHEME="MoyaSugar-macOS"      SDK="$MACOS_SDK"    ACTION="test"
    - SCHEME="MoyaSugar-tvOS"       SDK="$TVOS_SDK"     ACTION="test"
    - SCHEME="MoyaSugar-watchOS"    SDK="$WATCHOS_SDK"  ACTION="build"
    - SCHEME="RxMoyaSugar-iOS"      SDK="$IOS_SDK"      ACTION="test"
    - SCHEME="RxMoyaSugar-macOS"    SDK="$MACOS_SDK"    ACTION="test"
    - SCHEME="RxMoyaSugar-tvOS"     SDK="$TVOS_SDK"     ACTION="test"
    - SCHEME="RxMoyaSugar-watchOS"  SDK="$WATCHOS_SDK"  ACTION="build"

install:
  - bundle install --deployment
  - bundle exec pod --version
  - bundle exec pod repo update --silent
  - bundle exec pod install

script:
  - xcodebuild clean $ACTION -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty -c
